Config = {}
Config.MaxDistance = 1.0

Config.Sitable = {	
	-- BENCH
	[`prop_bench_01a`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_bench_01b`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_bench_01c`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_bench_02`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_bench_03`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_bench_04`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_bench_05`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_bench_06`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_bench_05`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_bench_08`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_bench_09`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_bench_10`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_bench_11`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_fib_3b_bench`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_ld_bench01`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_wait_bench_01`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
		
	-- CHAIR		
	[`hei_prop_heist_off_chair`]			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`hei_prop_hei_skid_chair`]				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_chair_01a`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_chair_01b`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_chair_02`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_chair_03`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_chair_04a`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_chair_04b`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_chair_05`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_chair_06`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_chair_05`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_chair_08`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_chair_09`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_chair_10`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_chateau_chair_01`]				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_clown_chair`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	--[`prop_cs_office_chair`]				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_direct_chair_01`]				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	--[`ba_Prop_Battle_Club_Chair_01`]		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.1, forwardOffset = 0.0, leftOffset = 0.0},	
	[`prop_direct_chair_02`]				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_gc_chair02`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	--[`prop_off_chair_01`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_off_chair_03`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_off_chair_04`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_off_chair_04b`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_off_chair_04_s`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_off_chair_05`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_old_deck_chair`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_old_wood_chair`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_rock_chair_01`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_skid_chair_01`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_skid_chair_02`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_skid_chair_03`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_sol_chair`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_wheelchair_01`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_wheelchair_01_s`]				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`p_armchair_01_s`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	--[`p_clb_officechair_s`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`p_dinechair_01_s`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`p_ilev_p_easychair_s`]				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`p_soloffchair_s`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`p_yacht_chair_01_s`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	--[`v_club_officechair`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`v_corp_bk_chair3`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`v_corp_cd_chair`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	--[`v_corp_offchair`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`v_ilev_chair02_ped`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`v_ilev_hd_chair`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`v_ilev_p_easychair`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`v_ret_gc_chair03`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_ld_farm_chair01`]				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_table_04_chr`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	--[`prop_table_05_chr`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_table_06_chr`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	--[`v_ilev_leath_chr`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_table_01_chr_a`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_table_01_chr_b`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_table_02_chr`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_table_03b_chr`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_table_03_chr`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_torture_ch_01`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`v_ilev_fh_dineeamesa`]				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`v_ilev_fh_kitchenstool`]				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`v_ilev_tort_stool`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`ex_prop_offchair_exec_01`]			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.1, forwardOffset = 0.0, leftOffset = 0.0},
	[`v_club_vuarmchair`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.1, forwardOffset = 0.0, leftOffset = 0.0},
	[`v_club_vu_chngestool`]				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.1, forwardOffset = 0.0, leftOffset = 0.0},
	[`v_res_m_l_chair1`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.1, forwardOffset = 0.0, leftOffset = 0.0},
	[`xm_prop_x17_corp_offchair`]			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.1, forwardOffset = 0.0, leftOffset = 0.0}, 
	[`apa_mp_h_stn_chairarm_24`]			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.1, forwardOffset = 0.0, leftOffset = 0.0},

	-- SEAT		
	[`hei_prop_yah_seat_01`]				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`hei_prop_yah_seat_02`]				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`hei_prop_yah_seat_03`]				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_waiting_seat_01`]				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_yacht_seat_01`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_yacht_seat_02`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_yacht_seat_03`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_hobo_seat_01`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.65, forwardOffset = 0.0, leftOffset = 0.0},
	--[`v_res_m_dinechair`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	
	-- COUCH		
	[`prop_rub_couch01`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`miss_rub_couch_01`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_ld_farm_couch01`]				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_ld_farm_couch02`]				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_rub_couch02`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_rub_couch03`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_rub_couch04`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
		
	-- SOFA		
	[`p_lev_sofa_s`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`p_res_sofa_l_s`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`p_v_med_p_sofa_s`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`p_yacht_sofa_01_s`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`v_ilev_m_sofa`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`v_res_tre_sofa_s`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`v_tre_sofa_mess_a_s`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`v_tre_sofa_mess_b_s`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`v_tre_sofa_mess_c_s`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`v_club_officesofa`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},

	-- MISC
	[`prop_roller_car_01`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_roller_car_02`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`prop_bar_stool_01`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.8, forwardOffset = 0.0, leftOffset = 0.0},
	[`hei_prop_yah_lounger`]				= { scenario = 'PROP_HUMAN_SEAT_SUNLOUNGER', verticalOffset = 0.49, forwardOffset = 0.33, leftOffset = -0.02},
	[`hei_mpheist_yacht_frnyat_3seat_h`]	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.49, forwardOffset = 0.33, leftOffset = -0.02},
	[`v_res_fh_kitnstool`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.49, forwardOffset = 0.33, leftOffset = -0.02},
	[`prop_toilet_01`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.49, forwardOffset = 0.33, leftOffset = -0.02},

	-- Strip Club
	[`v_club_stagechair`]					= { scenario = 'PROP_HUMAN_SEAT_STRIP_WATCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`v_club_barchair`]						= { scenario = 'PROP_HUMAN_SEAT_STRIP_WATCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`vw_prop_casino_track_chair_01`]		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`vw_prop_casino_chair_01a`]			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`v_ret_chair_white`]					= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`v_res_m_h_sofa`]						= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`ex_mp_h_off_chairstrip_01`]			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`ex_prop_offchair_exec_03`]			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	[`ex_prop_offchair_exec_04`]			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
	
	-- City Hall
	[`V_ILev_M_DineChair`]			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.5, forwardOffset = 0.0, leftOffset = 0.0},
}

Config.ChairModels =
{   --To add a new chair just add the model name here and tweak the offset
    { modelName = "p_clb_officechair_s", 			   sittingOffset = 0.38, zoffset = 0.0, },
    { modelName = "v_corp_offchair",  			 	   sittingOffset = 0.45, zoffset = 0.0, },
    { modelName = "prop_off_chair_01",  	    	   sittingOffset = 0.38, zoffset = 0.0, },
    { modelName = "prop_table_05_chr",   	      	   sittingOffset = 0.45, zoffset = 0.0, },
    { modelName = "prop_cs_office_chair", 	           sittingOffset = 0.38, zoffset = 0.0, },
    { modelName = "v_res_m_dinechair",   			   sittingOffset = 0.38, zoffset = 0.0, },
    { modelName = "v_club_officechair",   			   sittingOffset = 0.38, zoffset = 0.0, },
    { modelName = "ba_prop_battle_club_chair_01",  	   sittingOffset = 0.38, zoffset = 0.6, },
	{ modelName = "h4_prop_battle_club_chair_02",  	   sittingOffset = 0.53, zoffset = 0.6, },
	{ modelName = "bkr_prop_clubhouse_offchair_01a",   sittingOffset = 0.58, zoffset = 0.5, },
	{ modelName = "bkr_prop_weed_chair_01a",	       sittingOffset = 0.45, zoffset = 0.0, },
	{ modelName = "v_res_mbchair",	    			   sittingOffset = 0.55, zoffset = 0.0, },
	{ modelName = "v_res_m_armchair",	    		   sittingOffset = 0.55, zoffset = 0.0, },
	{ modelName = "v_res_m_l_chair1",	    		   sittingOffset = 0.45, zoffset = 0.0, },
	{ modelName = "v_ilev_m_dinechair",	    		   sittingOffset = 0.45, zoffset = 0.0, },
	{ modelName = "p_dinechair_01_s",	    		   sittingOffset = 0.45, zoffset = 0.0, },
	{ modelName = "prop_sol_chair",	    		       sittingOffset = 0.45, zoffset = 0.0, },
	{ modelName = "prop_chair_06",	    		       sittingOffset = 0.45, zoffset = 0.0, },
	{ modelName = "prop_chateau_chair_01",	    	   sittingOffset = 0.45, zoffset = 0.5, },
	{ modelName = "gabz_davispd_chair01",	    	   sittingOffset = 0.45, zoffset = 0.01,},
	{ modelName = "gabz_davispd_bench01",	    	   sittingOffset = 0.45, zoffset = 0.01,},
	{ modelName = "gabz_davispd_bench02",	    	   sittingOffset = 0.45, zoffset = 0.01,},
	{ modelName = "v_ret_chair",	    	 		   sittingOffset = 0.45, zoffset = 0.0, },
	{ modelName = "v_corp_lazychair",	    	 	   sittingOffset = 0.45, zoffset = 0.0, },
	{ modelName = "p_yacht_chair_01_s",	    	 	   sittingOffset = 0.55, zoffset = 0.5, },
	{ modelName = "imp_prop_impexp_offchair_01a",	   sittingOffset = 0.55, zoffset = 0.6, },
	{ modelName = "v_corp_bk_chair2",	  			   sittingOffset = 0.55, zoffset = 0.6, },
	{ modelName = "v_ilev_leath_chr",	  			   sittingOffset = 0.40, zoffset = 0.0, },
	
	--YJ Stools
	--{ modelName = "ba_prop_int_edgy_stool",	    	 	   sittingOffset = 0.55, zoffset = -0.2, },



	




	
	
}